version: '3'

services:
  database:
    image: postgres:11.7-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
volumes:
  postgres-db-volume:
